version = 1

test_patterns = [
    "vendor/*",
    "tools/vendor/*"
]

[[analyzers]]
name = "go"
enabled = true

  [analyzers.meta]
  import_paths = ["github.com/obalunenko/reelbet"]
  dependencies_vendored = true

[[transformers]]
name = "gofmt"
enabled = true
